# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: samllHw's blog 
email:  
description: > # this means to ignore newlines until "baseurl:"
    keep moving ，后台开发、服务器
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://smallHW89.github.io" # the base hostname & protocol for your site
twitter_username:  
github_username:  smallHW 

# Build settings
markdown: kramdown
